import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import express from 'express';
import request from 'supertest';
import fs from 'fs';
import { openDb } from '../db/index.js';
import { escanearGuardiaMl, estadoGuardiaMl, esClaveCubierta, listarGuardiaMl, retenerPedidoMl, pedidoMlRetenido, resolverRetencionPedidoMl } from '../lib/guardiaMl.js';
import { guardiaMlRouter } from '../routes/guardiaMl.js';

const FILE='./test/tmp-guardia.sqlite'; const now=()=>new Date().toISOString();
function cache(db, clave, sku='', stock=1){db.prepare(`INSERT INTO ml_publicaciones_cache (clave,item_id,variation_id,titulo,status,seller_sku,available_quantity,actualizado_en) VALUES (?,?,?,?,?,?,?,?)`).run(clave,clave.split('|')[0],clave.split('|')[1]||'',clave,'active',sku,stock,now())}
function catalogo(db,sku){db.prepare(`INSERT INTO catalogo_cache(id_woo,nombre,sku,tipo,stock,actualizado_en) VALUES (?,?,?,?,?,?)`).run(Math.floor(Math.random()*1e6),'P '+sku,sku,'simple',2,now())}
function decision(db,clave,sku,accion='confirmar'){db.prepare(`INSERT INTO sku_matcher_decisiones(clave,sku,accion,actualizado_en) VALUES (?,?,?,?)`).run(clave,sku,accion,now())}
describe('Guardia ML',()=>{let db;beforeEach(()=>{db=openDb(FILE);db.prepare("UPDATE guardia_ml_config SET modo='acciones' WHERE id=1").run()});afterEach(()=>{db.close();if(fs.existsSync(FILE))fs.unlinkSync(FILE)});
 it('abre solo la variación activa con stock sin vínculo exacto',()=>{catalogo(db,'FB-1');cache(db,'MLA1|a','',1);cache(db,'MLA1|b','FB-1',1);decision(db,'MLA1|b','FB-1');cache(db,'MLA2|', '',0);const r=escanearGuardiaMl(db);expect(r.total).toBe(1);expect(db.prepare('SELECT clave FROM guardia_ml_casos').all()).toEqual([{clave:'MLA1|a'}]);expect(esClaveCubierta(db,'MLA1|b')).toBe(true)});
 it('no permite que una omisión histórica cubra una clave vendible',()=>{cache(db,'MLA3|','',2);decision(db,'MLA3|',null,'omitir');escanearGuardiaMl(db);expect(db.prepare('SELECT estado FROM guardia_ml_casos WHERE clave=?').get('MLA3|').estado).toBe('abierto')});
 it('es idempotente y expone estado sano solo sin urgentes',()=>{catalogo(db,'FB-2');cache(db,'MLA4|','FB-2',1);decision(db,'MLA4|','FB-2');escanearGuardiaMl(db,'sistema',{lecturaMlConfirmada:true});expect(estadoGuardiaMl(db).sano).toBe(true);cache(db,'MLA5|','',1);escanearGuardiaMl(db);escanearGuardiaMl(db);expect(db.prepare('SELECT COUNT(*) n FROM guardia_ml_casos').get().n).toBe(1);expect(estadoGuardiaMl(db).sano).toBe(false)});
 it('retiene una venta sin cobertura y solo la libera con una acción explícita',()=>{retenerPedidoMl(db,{orderId:'ORD-1',items:[{item_id:'X'}],claves:['MLA6|v']});expect(pedidoMlRetenido(db,'ORD-1')).toBeTruthy();expect(db.prepare("SELECT estado FROM guardia_ml_casos WHERE clave='MLA6|v'").get().estado).toBe('abierto');expect(resolverRetencionPedidoMl(db,'ORD-1','ventas','liberado')).toBe(true);expect(pedidoMlRetenido(db,'ORD-1')).toBeUndefined()});
 it('reabre una excepción vencida conservando su responsable',()=>{cache(db,'MLA7|','',1);escanearGuardiaMl(db);db.prepare("UPDATE guardia_ml_casos SET estado='excepcion',responsable='ventas',excepcion_vence_en=? WHERE clave='MLA7|'").run(new Date(Date.now()-1000).toISOString());escanearGuardiaMl(db);const c=db.prepare("SELECT estado,responsable FROM guardia_ml_casos WHERE clave='MLA7|'").get();expect(c).toEqual({estado:'abierto',responsable:'ventas'});expect(db.prepare("SELECT evento FROM guardia_ml_eventos WHERE evento='excepcion_vencida'").get()).toBeTruthy()});
 it('no permite confirmar stock compartido sin dos vínculos válidos',()=>{catalogo(db,'FB-3');cache(db,'MLA8|a','FB-3',1);cache(db,'MLA8|b','FB-3',1);decision(db,'MLA8|a','FB-3');expect(db.prepare("SELECT COUNT(*) n FROM sku_matcher_decisiones WHERE sku='FB-3'").get().n).toBe(1);expect(db.prepare('SELECT COUNT(*) n FROM guardia_ml_stock_compartido').get().n).toBe(0)});
 it('un escaneo manual de cache no declara frescura de MercadoLibre',()=>{cache(db,'MLA9|','',1);escanearGuardiaMl(db);expect(db.prepare('SELECT ultimo_scan_exitoso_en FROM guardia_ml_config WHERE id=1').get().ultimo_scan_exitoso_en).toBeNull();expect(estadoGuardiaMl(db).degradado).toBe(true)});
 it('trata como descubierto un vínculo activo cuyo SKU ya no existe en Woo',()=>{cache(db,'MLA10|','FB-ELIMINADO',3);decision(db,'MLA10|','FB-ELIMINADO');escanearGuardiaMl(db);expect(db.prepare("SELECT motivo FROM guardia_ml_casos WHERE clave='MLA10|'").get().motivo).toBe('sin_cobertura')});
 it('usa seller_sku solo como señal de ventas, no como cobertura',()=>{db.exec("CREATE TABLE pedidos_cache (clave TEXT PRIMARY KEY,canal TEXT,ml_order_id TEXT,fecha TEXT,fecha_despacho_limite TEXT,items_json TEXT)");cache(db,'MLA11|','FB-SEÑAL',1);db.prepare('INSERT INTO pedidos_cache VALUES (?,?,?,?,?,?)').run('ml:o1','ml','o1',new Date().toISOString(),null,JSON.stringify([{seller_sku:'FB-SEÑAL'}]));escanearGuardiaMl(db);const c=listarGuardiaMl(db)[0];expect(c.ventas_30d).toBe(1);expect(esClaveCubierta(db,'MLA11|')).toBe(false)});
 it('bloquea por HTTP el segundo vínculo sin confirmación de stock compartido',async()=>{catalogo(db,'FB-12');cache(db,'MLA12|a','',1);cache(db,'MLA13|b','FB-12',1);decision(db,'MLA13|b','FB-12');escanearGuardiaMl(db);const caso=db.prepare("SELECT id FROM guardia_ml_casos WHERE clave='MLA12|a'").get();const app=express();app.use(express.json());app.use((req,_res,next)=>{req.user={username:'admin',is_admin:1};next()});app.use('/api/guardia-ml',guardiaMlRouter(db,{}));const res=await request(app).post(`/api/guardia-ml/casos/${caso.id}/vincular`).send({sku:'FB-12'});expect(res.status).toBe(409);expect(res.body.requiere_stock_compartido).toBe(true);expect(db.prepare("SELECT COUNT(*) n FROM sku_matcher_decisiones WHERE clave='MLA12|a'").get().n).toBe(0)});
 it('devuelve publicación completa y opciones Woo únicas para comparar',async()=>{db.prepare(`INSERT INTO ml_publicaciones_cache (clave,item_id,variation_id,titulo,status,seller_sku,variations_texto,thumbnail,permalink,available_quantity,actualizado_en) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).run('MLA14|','MLA14','','Cubierta Goodyear','active','SKU-REMOTO','Negra','https://img.ml/test.jpg','https://articulo.ml/MLA14',3,now());catalogo(db,'SKU-WOO');db.prepare("UPDATE catalogo_cache SET nombre='Cubierta Goodyear Negra',img='https://img.woo/test.jpg'").run();escanearGuardiaMl(db);const caso=db.prepare("SELECT id FROM guardia_ml_casos WHERE clave='MLA14|'").get();const app=express();app.use(express.json());app.use((req,_res,next)=>{req.user={username:'admin',is_admin:1};next()});app.use('/api/guardia-ml',guardiaMlRouter(db,{}));const res=await request(app).get(`/api/guardia-ml/casos/${caso.id}/opciones?q=goodyear`);expect(res.status).toBe(200);expect(res.body.data.publicacion).toMatchObject({item_id:'MLA14',thumbnail:'https://img.ml/test.jpg',seller_sku:'SKU-REMOTO'});expect(res.body.data.opciones).toHaveLength(1);expect(res.body.data.opciones[0]).toMatchObject({sku:'SKU-WOO',img:'https://img.woo/test.jpg'})});
});
