import { createRequire } from 'node:module';
const { chromium } = createRequire('/opt/fusionbikes/herramientas/')('playwright');
const b = await chromium.launch({ executablePath: '/opt/google/chrome/chrome', args: ['--no-sandbox'] });
const p = await (await b.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
const posts = []; p.on('request', (r) => { if (r.method() === 'POST') posts.push(r.url().split('/').slice(-2).join('/') + ' ' + r.postData()); });
await p.goto('http://127.0.0.1:3457/herramientas/bandeja-identidad/'); await p.waitForSelector('.caso-titulo');
const titulo = () => p.$eval('.caso-titulo', (e) => e.textContent.slice(0, 30));
const out = [];
await p.keyboard.press('j'); await p.keyboard.press('j'); await p.waitForTimeout(300); out.push('en caso 3: ' + await titulo());
await p.keyboard.press('1'); await p.waitForTimeout(200);
out.push('tras "1": posts=' + posts.length + ' sel=' + await p.$eval('input[type=radio]:checked', (e) => e.value).catch(() => 'ninguno'));
await p.keyboard.press('Enter'); await p.waitForTimeout(400);
out.push('tras Enter: posts=' + posts.length + ' -> ' + posts.join('|') + ' | ahora: ' + await titulo());
out.push('deshacer: ' + JSON.stringify(await p.evaluate(() => { const e = [...document.querySelectorAll('body *')].find((x) => /deshac/i.test(x.textContent) && x.children.length === 0 && x.offsetParent !== null); if (!e) return null; const r = e.getBoundingClientRect(); let n = e, pos = 'static'; while (n && n !== document.body) { const ps = getComputedStyle(n).position; if (ps === 'fixed' || ps === 'sticky') { pos = ps; break; } n = n.parentElement; } return { texto: e.textContent.slice(0, 60), top: Math.round(r.top), pos }; })));
await p.keyboard.press('z'); await p.waitForTimeout(400); out.push('tras z: posts=' + posts.length + ' | ' + posts[posts.length - 1]);
await p.keyboard.press('o'); await p.waitForTimeout(200); out.push('tras o (omitir): posts=' + posts.length + ' ahora: ' + await titulo());
await p.keyboard.press('?'); await p.waitForTimeout(300); out.push('tras ? (apartar): posts=' + posts.length);
await p.keyboard.press('x'); await p.waitForTimeout(300); out.push('tras x sin confirmable: posts=' + posts.length + ' ' + posts[posts.length - 1]);
await p.keyboard.press('/'); await p.waitForTimeout(200); out.push('tras /: buscador visible=' + await p.$('#input-buscar').then((e) => !!e));
console.log(out.join('\n'));
await b.close();
