import express from 'express';
import multer from 'multer';
import { guardarArchivo } from '../utils/storage.js';
import { listarTrabajos, listarRepuestosTrabajo, cambiarTrabajo, actualizarDiagnostico, moverRepuestoTrabajoIdempotente, devolverRepuestoTrabajoIdempotente } from '../lib/workshop.js';
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:15*1024*1024}});
const actor=req=>req.user?.username||'mobile';
const code=c=>({NOT_FOUND:404,VERSION_CONFLICT:409,LOCATION_NOT_FOUND:404,INSUFFICIENT_STOCK:409,INVALID_INPUT:422}[c]||400);
const reply=(res,x)=>res.status(x.ok?(x.repetido?200:201):code(x.code)).json(x);
export function mobileWorkshopRouter(db,auth){const r=express.Router();r.use(auth);r.get('/',(q,s)=>s.json({ok:true,data:listarTrabajos(db,q.query)}));r.get('/:id/parts',(q,s)=>s.json({ok:true,data:listarRepuestosTrabajo(db,q.params.id)}));r.post('/:id/state',(q,s)=>reply(s,cambiarTrabajo(db,q.params.id,{...q.body,actor:actor(q)})));r.post('/:id/diagnostic',(q,s)=>reply(s,actualizarDiagnostico(db,q.params.id,{...q.body,actor:actor(q)})));r.post('/parts/:partId/move',(q,s)=>reply(s,moverRepuestoTrabajoIdempotente(db,q.params.partId,{...q.body,actor:actor(q)})));r.post('/parts/:partId/return',(q,s)=>reply(s,devolverRepuestoTrabajoIdempotente(db,q.params.partId,{...q.body,actor:actor(q)})));r.post('/:id/evidence',upload.single('archivo'),(q,s)=>{const operationId=String(q.body?.operation_id||'').trim();if(!operationId)return s.status(422).json({ok:false,code:'INVALID_INPUT',error:'operation_id requerido'});if(!q.file)return s.status(422).json({ok:false,code:'INVALID_INPUT',error:'archivo requerido'});const job=db.prepare('SELECT codigo FROM workshop_jobs WHERE id=?').get(Number(q.params.id));if(!job)return s.status(404).json({ok:false,code:'NOT_FOUND'});const old=db.prepare('SELECT * FROM workshop_evidence WHERE operation_id=?').get(operationId);if(old)return s.json({ok:true,repetido:true,evidence:old});const saved=guardarArchivo({buffer:q.file.buffer,originalname:q.file.originalname,mimetype:q.file.mimetype,importador:'workshop',numeroPedido:job.codigo});const ts=new Date().toISOString();const result=db.prepare('INSERT INTO workshop_evidence(trabajo_id,referencia,tipo,operation_id,creado_por,creado_en) VALUES(?,?,?,?,?,?)').run(Number(q.params.id),saved.url,q.body?.tipo||'foto',operationId,actor(q),ts);return s.status(201).json({ok:true,evidence:db.prepare('SELECT * FROM workshop_evidence WHERE id=?').get(result.lastInsertRowid)})});return r}
