const STATES = new Set(['abierto','esperando_producto','en_revision','reparar','reemplazar','reembolsar','rechazado','cerrado']);
function now(){return new Date().toISOString()}
function op(v){const x=String(v||'').trim();if(!x||x.length>180)throw Error('operation_id obligatorio');return x}
function actor(v){return String(v||'sistema').trim()||'sistema'}
function version(v){const n=Number(v);if(!Number.isSafeInteger(n)||n<1)throw Error('expected_version inválida');return n}
function err(code){return {ok:false,code}}
export function crearGarantia(db,input={}){const operation_id=op(input.operation_id),motivo=String(input.motivo||'').trim(),responsable=String(input.responsable||'').trim();if(!motivo||!responsable)return err('INVALID_INPUT');const old=db.prepare('SELECT * FROM warranty_cases WHERE operation_id=?').get(operation_id);if(old)return {ok:true,repetido:true,caso:old};const ts=now();const r=db.prepare(`INSERT INTO warranty_cases(pedido_id,sku,estado,motivo,responsable,creado_por,creado_en,actualizado_en,operation_id) VALUES(?,?,?, ?,?,?,?,?,?)`).run(input.pedido_id||null,input.sku||null,'abierto',motivo,responsable,actor(input.creado_por),ts,ts,operation_id);return {ok:true,caso:db.prepare('SELECT * FROM warranty_cases WHERE id=?').get(r.lastInsertRowid)}}
export function listarGarantias(db,filters={}){const estado=String(filters.estado||'').trim();return db.prepare(`SELECT * FROM warranty_cases ${estado?'WHERE estado=?':''} ORDER BY actualizado_en ASC,id ASC`).all(...(estado?[estado]:[]))}
export function cambiarGarantia(db,id,input={}){const operation_id=op(input.operation_id),estado=String(input.estado||'').trim(),expected_version=version(input.expected_version),nota=String(input.nota||'').trim();if(!STATES.has(estado)||!nota)return err('INVALID_INPUT');const dup=db.prepare('SELECT * FROM warranty_events WHERE operation_id=?').get(operation_id);if(dup)return {ok:true,repetido:true,caso:db.prepare('SELECT * FROM warranty_cases WHERE id=?').get(Number(id))};return db.transaction(()=>{const before=db.prepare('SELECT * FROM warranty_cases WHERE id=?').get(Number(id));if(!before)return err('NOT_FOUND');if(before.expected_version!==expected_version)return err('VERSION_CONFLICT');const changed=db.prepare('UPDATE warranty_cases SET estado=?,resultado=CASE WHEN ? IN (\'reparar\',\'reemplazar\',\'reembolsar\',\'rechazado\') THEN ? ELSE resultado END,expected_version=expected_version+1,actualizado_en=? WHERE id=? AND expected_version=?').run(estado,estado,input.resultado||null,now(),Number(id),expected_version);if(!changed.changes)return err('VERSION_CONFLICT');const caso=db.prepare('SELECT * FROM warranty_cases WHERE id=?').get(Number(id));db.prepare('INSERT INTO warranty_events(caso_id,tipo,nota,actor,creado_en,operation_id) VALUES(?,?,?,?,?,?)').run(Number(id),`estado_${estado}`,nota,actor(input.actor),now(),operation_id);return {ok:true,caso}})()}
export function agregarEventoGarantia(db,id,input={}){const operation_id=op(input.operation_id),nota=String(input.nota||'').trim();if(!nota)return err('INVALID_INPUT');const dup=db.prepare('SELECT * FROM warranty_events WHERE operation_id=?').get(operation_id);if(dup)return {ok:true,repetido:true};if(!db.prepare('SELECT 1 FROM warranty_cases WHERE id=?').get(Number(id)))return err('NOT_FOUND');const r=db.prepare('INSERT INTO warranty_events(caso_id,tipo,nota,actor,creado_en,operation_id) VALUES(?,?,?,?,?,?)').run(Number(id),String(input.tipo||'comunicacion'),nota,actor(input.actor),now(),operation_id);return {ok:true,evento:db.prepare('SELECT * FROM warranty_events WHERE id=?').get(r.lastInsertRowid)}}
export function listarEventosGarantia(db,id){return db.prepare('SELECT * FROM warranty_events WHERE caso_id=? ORDER BY id').all(Number(id))}
export function inspeccionarGarantia(db,id,input={}){const operation_id=op(input.operation_id),expected_version=version(input.expected_version),resultado=String(input.resultado||'').trim();if(!resultado)return err('INVALID_INPUT');const dup=db.prepare('SELECT * FROM warranty_events WHERE operation_id=?').get(operation_id);if(dup)return {ok:true,repetido:true,caso:db.prepare('SELECT * FROM warranty_cases WHERE id=?').get(Number(id))};return db.transaction(()=>{const before=db.prepare('SELECT * FROM warranty_cases WHERE id=?').get(Number(id));if(!before)return err('NOT_FOUND');if(before.expected_version!==expected_version)return err('VERSION_CONFLICT');const ts=now();const changed=db.prepare("UPDATE warranty_cases SET estado='en_revision',inspeccion_resultado=?,inspeccion_por=?,inspeccion_en=?,expected_version=expected_version+1,actualizado_en=? WHERE id=? AND expected_version=?").run(resultado,actor(input.actor),ts,ts,Number(id),expected_version);if(!changed.changes)return err('VERSION_CONFLICT');const caso=db.prepare('SELECT * FROM warranty_cases WHERE id=?').get(Number(id));db.prepare('INSERT INTO warranty_events(caso_id,tipo,nota,actor,creado_en,operation_id) VALUES(?,?,?,?,?,?)').run(Number(id),'inspeccion',resultado,actor(input.actor),ts,operation_id);return {ok:true,caso}})()}
export function agregarAdjuntoGarantia(db,id,input={}){const operation_id=op(input.operation_id),referencia=String(input.referencia||'').trim(),tipo=String(input.tipo||'foto').trim();if(!referencia||!['foto','documento','comprobante','otro'].includes(tipo))return err('INVALID_INPUT');const dup=db.prepare('SELECT * FROM warranty_attachments WHERE operation_id=?').get(operation_id);if(dup)return {ok:true,repetido:true,adjunto:dup};if(!db.prepare('SELECT 1 FROM warranty_cases WHERE id=?').get(Number(id)))return err('NOT_FOUND');const r=db.prepare('INSERT INTO warranty_attachments(caso_id,tipo,referencia,nota,creado_por,creado_en,operation_id) VALUES(?,?,?,?,?,?,?)').run(Number(id),tipo,referencia,input.nota||null,actor(input.actor),now(),operation_id);return {ok:true,adjunto:db.prepare('SELECT * FROM warranty_attachments WHERE id=?').get(r.lastInsertRowid)}}
export function listarAdjuntosGarantia(db,id){return db.prepare('SELECT * FROM warranty_attachments WHERE caso_id=? ORDER BY id').all(Number(id))}
export function crearCompromisoGarantia(db,input={}){const operation_id=op(input.operation_id),sku=String(input.sku||'').trim(),cantidad=Number(input.cantidad);if(!sku||!Number.isSafeInteger(cantidad)||cantidad<1)return err('INVALID_INPUT');const old=db.prepare('SELECT * FROM warranty_stock_commitments WHERE operation_id=?').get(operation_id);if(old)return {ok:true,repetido:true,compromiso:old};if(!db.prepare('SELECT 1 FROM warranty_cases WHERE id=?').get(Number(input.caso_id)))return err('NOT_FOUND');const ts=now();const r=db.prepare('INSERT INTO warranty_stock_commitments(caso_id,sku,cantidad,estado,creado_por,creado_en,actualizado_en,operation_id) VALUES(?,?,?,\'comprometido\',?,?,?,?)').run(Number(input.caso_id),sku,cantidad,actor(input.creado_por),ts,ts,operation_id);return {ok:true,compromiso:db.prepare('SELECT * FROM warranty_stock_commitments WHERE id=?').get(r.lastInsertRowid)}}
export function listarCompromisosGarantia(db,casoId){return db.prepare('SELECT * FROM warranty_stock_commitments WHERE caso_id=? ORDER BY id').all(Number(casoId))}
export function cambiarCompromisoGarantia(db,id,input={}){const operation_id=op(input.operation_id),expected_version=version(input.expected_version),estado=String(input.estado||'').trim(),nota=String(input.nota||'').trim();if(!['liberado','consumido'].includes(estado)||!nota)return err('INVALID_INPUT');const dup=db.prepare('SELECT * FROM warranty_events WHERE operation_id=?').get(operation_id);if(dup)return {ok:true,repetido:true,compromiso:db.prepare('SELECT * FROM warranty_stock_commitments WHERE id=?').get(Number(id))};return db.transaction(()=>{const before=db.prepare('SELECT * FROM warranty_stock_commitments WHERE id=?').get(Number(id));if(!before)return err('NOT_FOUND');if(before.expected_version!==expected_version||before.estado!=='comprometido')return err('VERSION_CONFLICT');const ts=now();const changed=db.prepare('UPDATE warranty_stock_commitments SET estado=?,expected_version=expected_version+1,actualizado_en=? WHERE id=? AND expected_version=? AND estado=\'comprometido\'').run(estado,ts,Number(id),expected_version);if(!changed.changes)return err('VERSION_CONFLICT');const compromiso=db.prepare('SELECT * FROM warranty_stock_commitments WHERE id=?').get(Number(id));db.prepare('INSERT INTO warranty_events(caso_id,tipo,nota,actor,creado_en,operation_id) VALUES(?,?,?,?,?,?)').run(compromiso.caso_id,`compromiso_${estado}`,nota,actor(input.actor),ts,operation_id);return {ok:true,compromiso}})()}
