import {readFileSync} from 'node:fs';
const catalog=JSON.parse(readFileSync(new URL('./andreani/data/catalog.json',import.meta.url)));
const base='/herramientas/gestion-vps/andreani/';
export const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function andreaniView(data,query,csrf){
 const e=escape,select=(a,b)=>String(a)===String(b)?' selected':'',status=query.get('status')||'all';
 const pageLink=page=>{const q=new URLSearchParams(query);q.set('page',page);return base+'?'+q;};
 const config={url:base+'api',csrf,packages:catalog.packages,declaredValue:'30000',profiles:{bike:{profile:'bike',saved:'',height:'30',width:'20',depth:'40',weight:'9000'},other:{profile:'other',saved:'',height:'12',width:'25',depth:'30',weight:'1000'}}};
 return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Envíos Andreani · Herramientas</title><link rel="stylesheet" href="/herramientas/lib/theme.css"><link rel="stylesheet" href="/herramientas/lib/components.css"><link rel="stylesheet" href="/herramientas/gestion-vps/assets/management.css"><link rel="stylesheet" href="/herramientas/gestion-vps/assets/andreani.css"></head><body class="fm-home">
 <header class="fm-top"><a class="fm-brand" href="/herramientas/home/">FUSION <span>BIKES</span></a><a class="ui-btn" href="/herramientas/gestion-vps/">← Gestión</a></header><main class="fm-main fbam">
 <p class="fm-eyebrow">HERRAMIENTAS · LOGÍSTICA</p><h1>Envíos Andreani</h1><p class="fm-intro">Prepará tus pedidos y descargá el Excel de carga masiva.</p>
 <p class="fbam-sync ${data.status.stale?'warn':''}">Pedidos sincronizados: ${e(new Date(data.status.orders_at).toLocaleString('es-AR',{timeZone:'America/Argentina/Buenos_Aires',hourCycle:'h23'}))}${data.status.stale?' · Sincronización atrasada; exportación pausada.':''}</p>
 <div class="fbam-guide"><b>1. Seleccioná pedidos</b><span>2. Revisá destinatario y bultos</span><span>3. Exportá el Excel</span></div>
 <p><a class="button" href="https://pymes.andreani.com/" target="_blank" rel="noopener noreferrer">Ingresar a Andreani PyMEs ↗</a></p><p class="description">Subí el Excel a Andreani para contratar el envío y obtener las etiquetas. Valor declarado: $30.000 ARS por bulto.</p>
 <form method="get" action="${base}" class="fbam-filters"><label>Estado<select name="status"><option value="all"${select(status,'all')}>Todos</option>${data.options.statuses.map(s=>`<option value="${e(s.key.slice(3))}"${select(status,s.key.slice(3))}>${e(s.label)}</option>`).join('')}</select></label><label>Desde<input type="date" name="from" value="${e(query.get('from'))}"></label><label>Hasta<input type="date" name="to" value="${e(query.get('to'))}"></label><label>ID del pedido<input type="number" name="order_id" min="1" value="${e(query.get('order_id'))}" placeholder="Ej. 70680"></label><button class="button" type="submit">Buscar</button></form>
 <form id="fbam-export"><div class="fbam-toolbar"><strong><span id="fbam-selected">0</span> seleccionados</strong><label>Filtrar esta página por envío<input id="fbam-method" type="search" placeholder="Andreani, envío gratis…"></label><label><input type="checkbox" name="allow_repeat"> Permitir reexportar</label><button type="submit" class="button button-primary" id="fbam-download" disabled>Descargar Excel Andreani</button></div>
 <p id="fbam-export-status" role="status" hidden></p><div class="fbam-table-wrap"><table class="fbam-table"><thead><tr><th><input type="checkbox" id="fbam-all" aria-label="Seleccionar pedidos visibles"></th><th>Pedido / fecha</th><th>Productos</th><th>Cliente / envío</th><th>Preparación</th><th>Acción</th></tr></thead><tbody>${data.rows.map(d=>`<tr data-id="${e(d.id)}" data-method="${e(d.method)}" data-exported="${d.exported?'1':'0'}" data-ready="${d.errors.length?'0':'1'}"><td><input class="fbam-pick" type="checkbox" value="${e(d.id)}" aria-label="Seleccionar pedido ${e(d.number)}"></td><td><a href="https://fusionbikes.com.ar/wp-admin/admin.php?page=wc-orders&amp;action=edit&amp;id=${e(d.id)}" target="_blank" rel="noopener"><strong>#${e(d.number)}</strong></a><small>${e(d.date)}</small><span class="fbam-tag">${e(d.status)}</span></td><td class="fbam-products">${d.products.map(p=>`<div>${e(p)}</div>`).join('')}</td><td><b>${e(d.draft.first_name+' '+d.draft.last_name)}</b><small>${e(d.address_original)}</small><small>${e(d.method||'Sin método de envío')}</small></td><td><span class="fbam-ready fbam-tag ${d.errors.length?'warn':'ok'}">${d.errors.length?'Revisar datos':'Listo para exportar'}</span><small class="fbam-export-date">${d.exported?'Exportado: '+e(d.exported):'Sin exportar'}</small></td><td><button type="button" class="button fbam-review" data-id="${e(d.id)}">Revisar</button></td></tr>`).join('')||'<tr><td colspan="6">No hay pedidos con estos filtros.</td></tr>'}</tbody></table></div></form>
 <nav class="fbam-pagination" aria-label="Páginas de pedidos">${data.page>1?`<a class="button" href="${e(pageLink(data.page-1))}">← Anterior</a>`:''}<span>${data.total} pedidos · Página ${data.page} de ${Math.max(1,data.pages)}</span>${data.page<data.pages?`<a class="button" href="${e(pageLink(data.page+1))}">Siguiente →</a>`:''}</nav>
 <details class="fbam-settings"><summary>Perfiles automáticos de bultos</summary><form id="fbam-settings-form"><p>Bicicletas: 30 × 20 × 40 cm y 9.000 g. Resto: 12 × 25 × 30 cm y 1.000 g. Revisá y ajustá las medidas del paquete real en cada pedido.</p><label>Categorías de bicicletas (incluye subcategorías)<select name="bike_categories" multiple size="6">${data.options.categories.map(c=>`<option value="${e(c.id)}"${data.settings.bike_categories.includes(c.id)?' selected':''}>${e(c.name)}</option>`).join('')}</select></label><p>Usá Ctrl o Cmd para seleccionar varias. Sin selección se buscan las categorías Bicicletas por nombre.</p><button class="button" type="submit">Guardar perfiles</button><span id="fbam-settings-status" role="status"></span></form></details>
 <p class="description">Las nuevas revisiones y exportaciones se guardan en Herramientas. Prepará cada pedido desde este panel para mantener un único registro. Las marcas anteriores de la tienda llegan con la sincronización.</p><p class="description">Plantilla y listas del generador actual (25/09/2026). El archivo descargable se conserva 24 horas; la marca de exportación permanece.</p>
 </main><dialog id="fbam-dialog" aria-labelledby="fbam-dialog-title"><div class="fbam-modal-head"><h2 id="fbam-dialog-title">Revisar envío</h2><button type="button" id="fbam-close" aria-label="Cerrar">×</button></div><div id="fbam-editor"></div></dialog><script>const FBAM=${JSON.stringify(config).replace(/</g,'\\u003c')};</script><script src="/herramientas/gestion-vps/assets/andreani.js"></script></body></html>`;
}
