<?php
define('FM_ANDREANI_TEST',true);require $argv[1].'/worker.php';
$count=0;function check($ok,$message){global $count;if(!$ok)throw new RuntimeException($message);$count++;}
function rejects($fn,$part){try{$fn();}catch(RuntimeException $e){check(str_contains($e->getMessage(),$part),$e->getMessage());return;}throw new RuntimeException('Expected rejection: '.$part);}
$catalog=FBAM_Data::catalog();
$address=['first_name'=>'Prueba','last_name'=>'Migración','address_1'=>'San Martín 123','address_2'=>'Piso 2','city'=>'Ciudad','state'=>'B','country'=>'AR','postcode'=>'1000','email'=>'qa@example.invalid','phone'=>'+54 9 11 5555 1234'];
$order=['id'=>1,'number'=>'QA-1','status'=>'processing','currency'=>'USD','created_at'=>'2026-10-05T12:00:00Z','billing'=>$address,'shipping'=>array_merge($address,['first_name'=>'Destino']),'shipping_document'=>'12.345.678','shipping_methods'=>['Envío QA'],'items'=>[['product_id'=>9,'variation_id'=>10,'quantity'=>2,'name'=>'Producto QA']],'andreani'=>['draft'=>null,'exported_at'=>'']];
$context=['orders'=>[$order],'settings'=>['bike_categories'=>[62]],'options'=>['timezone'=>'America/Argentina/Buenos_Aires','categories'=>[['id'=>62,'name'=>'Bicicletas','slug'=>'bicicletas']],'states'=>['AR'=>['B'=>'Buenos Aires']],'statuses'=>[['key'=>'wc-processing','label'=>'Procesando']]],'products'=>['9'=>['id'=>9,'exists'=>true,'parent_id'=>0,'virtual'=>false,'category_ids'=>[62]],'10'=>['id'=>10,'exists'=>true,'parent_id'=>9,'virtual'=>false,'category_ids'=>[62]]]];
$row=fm_process(['action'=>'draft']+$context)[0];
check($row['draft']['observations']==='Pedido #QA-1; Piso 2','order number plus delivery notes');
$many=$context;$many['orders'][0]['items'][]=array_merge($order['items'][0],['name'=>'Segundo producto QA']);
check(fm_process(['action'=>'draft']+$many)[0]['draft']['observations']==='Pedido #QA-1; Piso 2','one order number for multiple products');
check($row['draft']['first_name']==='Destino','shipping recipient');check($row['draft']['dni']==='12345678','DNI');check($row['date']==='05/10/2026 09:00','timezone');check($row['draft']['street']==='San Martín'&&$row['draft']['number']==='123','address split');check($row['auto_package']['profile']==='bike','parent bicycle category');check($row['draft']['packages'][0]['value']==='30000','fixed ARS value regardless order currency');check(!$row['draft']['reviewed'],'manual review');check($row['draft']['phone_code']==='11'&&$row['draft']['phone_number']==='55551234','phone');
$virtual=$context;$virtual['products']['10']['virtual']=true;check(fm_process(['action'=>'draft']+$virtual)[0]['auto_package']['profile']==='other','virtual ignored');
$fallback=$context;$fallback['orders'][0]['shipping']['address_1']='';check(fm_process(['action'=>'draft']+$fallback)[0]['draft']['first_name']==='Prueba','complete billing fallback');
$draft=$row['draft'];$draft['destination']=$catalog['destinations'][0];$draft['reviewed']=true;$draft['packages'][]=$draft['packages'][0];$draft['packages'][0]['value']='999';
$normalized=fm_process(['action'=>'normalize','draft'=>$draft]+$context);check(!$normalized['errors'],'valid draft');check($normalized['draft']['packages'][0]['value']==='30000','normalizes value');$draft=$normalized['draft'];
check(fm_process(['action'=>'normalize','draft'=>$draft]+$context)['draft']['observations']==='Pedido #QA-1; Piso 2','save does not duplicate order number');
$legacy=$context;$legacy['orders'][0]['andreani']['draft']=array_merge($draft,['observations'=>'Llamar al llegar']);check(fm_process(['action'=>'draft']+$legacy)[0]['draft']['observations']==='Pedido #QA-1; Llamar al llegar','existing drafts retain operator notes');
$punctuation=$context;$punctuation['orders'][0]['items'][0]['name']='Producto; color &amp; talla';$punctuationDraft=$draft;$punctuationDraft['observations']='Producto; color & talla; Piso 2';check(fm_process(['action'=>'normalize','draft'=>$punctuationDraft]+$punctuation)['draft']['observations']==='Pedido #QA-1; Piso 2','replaces old punctuated title without deleting delivery notes');
$legacy['orders'][0]['andreani']['draft']['observations']='Producto QA; Llamar al llegar';check(fm_process(['action'=>'draft']+$legacy)[0]['draft']['observations']==='Pedido #QA-1; Llamar al llegar','replaces saved automatic title');
$legacy['orders'][0]['andreani']['draft']['observations']='Piso 2; Producto QA; Llamar al llegar';check(fm_process(['action'=>'draft']+$legacy)[0]['draft']['observations']==='Pedido #QA-1; Piso 2; Llamar al llegar','replaces old title after address complement');
$manualNotes=$draft;$manualNotes['observations']='Consultar por Producto QA antes de entregar';check(fm_process(['action'=>'normalize','draft'=>$manualNotes]+$context)['draft']['observations']==='Pedido #QA-1; Consultar por Producto QA antes de entregar','preserves product mention within operator sentence');
$oldSmall=$draft;$oldSmall['packages']=[array_merge(FBAM_Data::package_profiles()['other'],['value'=>'30000'])];$legacy=$context;$legacy['orders'][0]['andreani']['draft']=$oldSmall;
$corrected=fm_process(['action'=>'draft']+$legacy)[0]['draft'];check($corrected['packages'][0]['profile']==='bike'&&$corrected['packages'][0]['weight']==='9000','old single small preset becomes bicycle');check($corrected['reviewed'],'automatic preset refresh preserves recipient review');check($corrected['packages'][0]['profile_mode']==='auto','legacy preset tracked as automatic');
$saved=fm_process(['action'=>'normalize','draft'=>$oldSmall]+$context)['draft'];check($saved['packages'][0]['height']==='30','old open editor cannot save obsolete small preset');
$fixed=$oldSmall;$fixed['packages'][0]['profile_mode']='fixed';check(fm_process(['action'=>'normalize','draft'=>$fixed]+$context)['draft']['packages'][0]['weight']==='1000','explicit fixed small parcel preserved');
$custom=$oldSmall;$custom['packages'][0]=['profile'=>'manual','saved'=>'','height'=>'81','width'=>'24','depth'=>'140','weight'=>'13000','value'=>'30000'];check(fm_process(['action'=>'normalize','draft'=>$custom]+$context)['draft']['packages'][0]['height']==='81','custom dimensions preserved');
$box=$custom;$box['packages'][0]['saved']=$catalog['packages'][0];check(fm_process(['action'=>'normalize','draft'=>$box]+$context)['draft']['packages'][0]['saved']===$catalog['packages'][0],'saved package preserved');
$multiple=$oldSmall;$multiple['packages'][]=$oldSmall['packages'][0];check(fm_process(['action'=>'normalize','draft'=>$multiple]+$context)['draft']['packages'][1]['weight']==='1000','existing multi-parcel choice preserved');
$automatic=$fixed;$automatic['packages'][0]['profile_mode']='auto';check(fm_process(['action'=>'normalize','draft'=>$automatic]+$context)['draft']['packages'][0]['profile']==='bike','explicit automatic selection recalculates');
$nonbike=$context;$nonbike['products']['10']['virtual']=true;check(fm_process(['action'=>'normalize','draft'=>$automatic]+$nonbike)['draft']['packages'][0]['profile']==='other','automatic profile follows changed classification');
$legacyExcel=fm_process(['action'=>'export']+$legacy);$legacyFile=$argv[2].'.legacy.xlsx';file_put_contents($legacyFile,$legacyExcel['xlsx']);$legacyZip=new ZipArchive();$legacyZip->open($legacyFile);$legacyDoc=new DOMDocument();$legacyDoc->loadXML($legacyZip->getFromName('xl/worksheets/sheet1.xml'));$xp=new DOMXPath($legacyDoc);$xp->registerNamespace('x','http://schemas.openxmlformats.org/spreadsheetml/2006/main');check($xp->evaluate('string(//x:c[@r="B3"]/x:v)')==='9000','export repairs old small bicycle weight');check($xp->evaluate('string(//x:c[@r="C3"]/x:v)')==='30','export repairs old small bicycle height');$legacyZip->close();unlink($legacyFile);
$invalid=$draft;$invalid['dni']='20123456789';check(count(fm_process(['action'=>'normalize','draft'=>$invalid]+$context)['errors'])>0,'CUIT rejected');
$incomplete=$draft;$incomplete['packages'][0]=['profile'=>'manual','saved'=>'','weight'=>'','height'=>'','width'=>'','depth'=>'','value'=>'30000'];$repaired=fm_process(['action'=>'normalize','draft'=>$incomplete]+$context);check(!$repaired['draft']['reviewed'],'auto repaired draft must be reviewed again');check($repaired['draft']['packages'][0]['height']==='30','repairs old empty parcels');
$orders=[];foreach(['home','branch','today'] as $index=>$service){$o=$order;$o['id']=$index+1;$o['number']='QA-'.($index+1);$d=$draft;$d['service']=$service;$d['branch']=$catalog['branches'][0];$d['destination']=$service==='today'?$catalog['today'][0]:$catalog['destinations'][0];$d['observations']='=HYPERLINK("test")';$o['andreani']['draft']=$d;$orders[]=$o;}
$ctx=$context;$ctx['orders']=$orders;$excel=fm_process(['action'=>'export']+$ctx);check(substr($excel['xlsx'],0,2)==='PK','xlsx bytes');file_put_contents($argv[2],$excel['xlsx']);
$ctx['orders'][0]['status']='cancelled';rejects(fn()=>fm_process(['action'=>'export']+$ctx),'estado no apto');$ctx['orders'][0]['status']='processing';$ctx['orders'][0]['andreani']['draft']['reviewed']=false;rejects(fn()=>fm_process(['action'=>'export']+$ctx),'Confirmá');
rejects(fn()=>FBAM_Exporter::generate(['home'=>array_fill(0,498,[])]),'497 filas');
$_SERVER['REQUEST_METHOD']='POST';$_SERVER['REQUEST_URI']='/fusion-andreani-worker/worker.php';$body='{"action":"phone"}';$key=getenv('FUSION_MANAGEMENT_SIGNING_KEY');$claim=base64_encode(json_encode(['user'=>'qa','method'=>'POST','uri'=>$_SERVER['REQUEST_URI'],'time'=>time(),'sha256'=>hash('sha256',$body)]));$_SERVER['HTTP_X_FUSION_CLAIM']=$claim;$_SERVER['HTTP_X_FUSION_SIGNATURE']=hash_hmac('sha256',$claim,$key);check(fm_auth($body),'valid HMAC');check(!fm_auth($body.' '),'tampered body');$_SERVER['REQUEST_URI']='/other';check(!fm_auth($body),'wrong URI');
echo json_encode(['assertions'=>$count,'synthetic_xlsx_bytes'=>strlen($excel['xlsx'])])."\n";
