export function pdfView(token) {
  const fields=(side,values)=>['weight','width','height','length'].map((key,index)=>`<div class="pdf-field"><label for="${side}-${key}">${['Peso (Gr)','Ancho (Cm)','Alto (Cm)','Largo (Cm)'][index]}</label><input id="${side}-${key}" name="${side}-${key}" data-rule-input form="pdf-form" type="text" inputmode="numeric" pattern="[0-9]{1,${index===0?6:4}}" maxlength="${index===0?6:4}" value="${values[index]}" required aria-describedby="rule-help"></div>`).join('');
  return `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Corregir etiquetas PDF · Herramientas</title>
<meta name="fusion-csrf" content="${token}">
<link rel="stylesheet" href="/herramientas/lib/theme.css"><link rel="stylesheet" href="/herramientas/lib/components.css">
<link rel="stylesheet" href="/herramientas/gestion-vps/assets/management.css">
<link rel="stylesheet" href="/herramientas/gestion-vps/assets/pdf-corrector.css">
<script src="/herramientas/gestion-vps/assets/pdf-corrector.js" defer></script></head>
<body class="fm-home"><header class="fm-top"><a class="fm-brand" href="/herramientas/home/">FUSION <span>BIKES</span></a><a class="ui-btn" href="/herramientas/home/">← Herramientas</a></header>
<main class="fm-main pdf-main"><p class="fm-eyebrow">LOGÍSTICA · ANDREANI</p><h1>Corregir etiquetas PDF</h1>
<p class="fm-intro">Indicá qué peso y medidas tiene el PDF y por cuáles querés reemplazarlos. Después elegí el archivo para corregirlo.</p>
<section class="ui-card pdf-rule" aria-labelledby="rule-title"><h2 id="rule-title">Elegí los reemplazos</h2><div class="pdf-rule-grid"><fieldset><legend>Datos que tiene el PDF</legend><div class="pdf-fields">${fields('before',['9000','20','30','40'])}</div></fieldset><span class="pdf-arrow" aria-hidden="true">→</span><fieldset><legend>Reemplazar por</legend><div class="pdf-fields">${fields('after',['15000','25','70','150'])}</div></fieldset></div><p id="rule-help" class="pdf-note">Completá los cuatro datos de entrada y salida con enteros positivos. Peso: hasta 6 dígitos. Medidas: hasta 4. Solo se cambian las etiquetas que coinciden con los cuatro datos de entrada.</p><button id="pdf-reset-rule" class="ui-btn" type="button">Restaurar valores habituales</button><p class="pdf-note">Se conserva el tamaño de impresión y el resto de cada etiqueta. El cambio se aplica al PDF; no actualiza el envío registrado en Andreani.</p></section>
<section class="ui-card pdf-upload" aria-labelledby="upload-title"><h2 id="upload-title">Elegí tu archivo</h2><form id="pdf-form"><label for="pdf-file">PDF de etiquetas de Andreani</label><input id="pdf-file" type="file" accept="application/pdf,.pdf" required aria-describedby="file-help"><p id="file-help" class="pdf-note">Un PDF por vez · hasta 10 MB y 300 páginas. Los archivos se procesan sin guardarse en el servidor.</p><button id="pdf-submit" class="ui-btn ui-btn--primary" type="submit">Corregir etiquetas</button></form><div id="pdf-status" class="pdf-status" role="status" aria-live="polite" hidden></div></section>
<section id="pdf-result" class="ui-card pdf-result" aria-labelledby="result-title" hidden><h2 id="result-title" tabindex="-1">PDF corregido</h2><p id="pdf-summary"></p><p id="pdf-pages" class="pdf-note"></p><div class="pdf-actions"><button id="pdf-open" class="ui-btn" type="button">Ver PDF corregido</button><button id="pdf-print" class="ui-btn" type="button">Imprimir</button><a id="pdf-download" class="ui-btn ui-btn--primary" download>Descargar PDF</a></div><p class="pdf-note">Para mantener el tamaño de la etiqueta, imprimí en tamaño real (100 %). También podés descargar el PDF e imprimirlo desde tu visor habitual.</p><div id="pdf-preview" aria-label="Vista previa del PDF corregido"><div class="pdf-pagination"><button id="pdf-previous" class="ui-btn" type="button" aria-label="Página anterior">←</button><label class="pdf-page-label" for="pdf-page-select">Página</label><select id="pdf-page-select" aria-label="Página de la vista previa"></select><button id="pdf-next" class="ui-btn" type="button" aria-label="Página siguiente">→</button></div><canvas id="pdf-canvas" role="img" tabindex="0"></canvas></div></section>
</main></body></html>`;
}
