import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {mkdtempSync,rmSync} from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';
import {createPos,createStoreClient} from './pos-vps.mjs';import {createGateway,prefix,allowedTarget} from './gateway.mjs';import {csrfToken} from './andreani.mjs';
const op='11111111-1111-4111-8111-111111111111';
function fixture(t){const tmp=mkdtempSync(path.join(os.tmpdir(),'fusion-pos-'));t.after(()=>rmSync(tmp,{recursive:true,force:true}));let calls=[],hasOrder=false;
 const pos=createPos({statePath:path.join(tmp,'test.sqlite'),catalog:async()=>({id:70394,name:'Local product',price:4450000,stock:1}),store:async(d,u)=>{calls.push([d,u]);if(d.action==='prepare')return {order_id:0,payment_url:'https://fusionbikes.com.ar/?fbpos_vps_open='+'a'.repeat(48),status_url:'vps'};if(d.action==='release'&&hasOrder)throw Error('must not release an order');return d.action==='release'?{released:true}:hasOrder?{order_id:12,paid:false}:{order_id:0,status:'Pendiente'};}});
 return {pos,calls,setOrder:()=>hasOrder=true};
}
test('Drafts persist locally, hydrate local products, and reject stale versions',async t=>{const {pos,calls}=fixture(t);assert.equal((await pos('draft-read',{},'one')).version,0);assert.equal((await pos('draft-write',{version:0,sale:{items:[{id:70394,qty:1}],customer:{name:'Test'},note:'Hola'}},'one')).version,1);await assert.rejects(pos('draft-write',{version:0,sale:{}},'one'),e=>e.code==='draft_conflict');const d=await pos('draft-read',{},'one');assert.equal(d.products[0].price,4450000);assert.equal(d.sale.note,'Hola');assert.equal((await pos('draft-read',{},'two')).sale.items.length,0);assert.equal(calls.length,0);});
test('Checkout is idempotent and bound to operator; reset releases only before an order exists',async t=>{const {pos,calls,setOrder}=fixture(t);const sale={items:[{id:70394,qty:1}],customer:{name:'Test'}};await pos('draft-write',{version:0,sale},'one');const input={operation:op,items:sale.items,customer_name:'Test'};const a=await pos('prepare',input,'one');assert.deepEqual(await pos('prepare',input,'one'),a);assert.equal(calls.length,1);await assert.rejects(pos('status',{operation:op},'two'),e=>e.status===404);await assert.rejects(pos('prepare',{...input,items:[{id:70394,qty:2}]},'one'),e=>e.code==='operation_conflict');assert.equal((await pos('draft-read',{},'one')).sale.payment_url,a.payment_url);setOrder();await pos('reset',{version:1},'one');assert.equal(calls.filter(([d])=>d.action==='release').length,0);});
test('Store requests sign exact body and do not send browser cookies or credentials in URL',async()=>{const key='s'.repeat(96);let seen=0;const client=createStoreClient(key,'https://fusionbikes.com.ar',async(url,init)=>{seen++;assert.equal(url,'https://fusionbikes.com.ar/wp-json/fusion-vps-pos/v1/command');assert.equal(init.headers.cookie,undefined);assert.equal(init.headers['x-fusion-pos-signature'],crypto.createHmac('sha256',key).update(init.headers['x-fusion-pos-time']+'\n'+crypto.createHash('sha256').update(init.body).digest('hex')).digest('hex'));assert.equal(JSON.parse(init.body).actor.length,64);return new Response('{"order_id":0}');});await client({operation:op,action:'status'},'user');assert.equal(seen,1);});
test('A preparation rejected before creation can be cleared without hiding outages',async t=>{const tmp=mkdtempSync(path.join(os.tmpdir(),'fusion-pos-'));t.after(()=>rmSync(tmp,{recursive:true,force:true}));let outage=false;const pos=createPos({statePath:path.join(tmp,'test.sqlite'),catalog:async()=>({}),store:async()=>{throw Object.assign(Error('Missing'),{code:outage?'bridge_unavailable':'operation_missing'});}});await pos('draft-write',{version:0,sale:{items:[{id:1,qty:1}]}},'one');await assert.rejects(pos('prepare',{operation:op,items:[{id:1,qty:1}]},'one'));outage=true;await assert.rejects(pos('reset',{version:1},'one'),e=>e.code==='bridge_unavailable');outage=false;assert.equal((await pos('reset',{version:1},'one')).version,2);assert.equal((await pos('draft-read',{},'one')).sale.operation,'');});
test('POS gateway requires current admin, Origin, CSRF and exact routes; ARCA retained',async t=>{let admin=true,calls=0;const secret='x'.repeat(64),cookie='connect.sid=qa';const auth=http.createServer((q,r)=>r.end(JSON.stringify({ok:true,user:'qa',is_admin:admin})));await new Promise(r=>auth.listen(0,'127.0.0.1',r));const gw=createGateway({secret,upstreamHost:'127.0.0.1',authPort:auth.address().port,posEnabled:true,posHandle:async()=>{calls++;return {version:1};}});await new Promise(r=>gw.listen(0,'127.0.0.1',r));t.after(()=>{gw.close();auth.close();});const url='http://127.0.0.1:'+gw.address().port+prefix+'/wp-json/fbpos/v2/draft';const headers={cookie,origin:'https://herramientas.fusionbikes.com.ar','x-fusion-csrf':csrfToken(secret,'qa',cookie),'content-type':'application/json'};const send=h=>fetch(url,{method:'PUT',headers:h,body:'{}'});assert.equal((await send({...headers,origin:'https://evil.invalid'})).status,403);assert.equal((await send({...headers,'x-fusion-csrf':'bad'})).status,403);admin=false;assert.equal((await send(headers)).status,403);admin=true;assert.equal(calls,0);assert.equal((await send(headers)).status,200);assert.equal(calls,1);assert.equal(allowedTarget(prefix+'/wp-json/fbpos/v2/prepare?operation=x','POST'),null);assert.ok(allowedTarget(prefix+'/wp-json/fusion-arca/v1/invoices/1/emit','POST'));assert.equal(allowedTarget(prefix+'/wp-json/fbpos/v2/manual-receipt','POST').action,'manual-receipt');});

test('Commercial quote is cached; selected plan and reviewed total survive prepare and draft',async t=>{
 const tmp=mkdtempSync(path.join(os.tmpdir(),'fusion-plans-'));t.after(()=>rmSync(tmp,{recursive:true,force:true}));const calls=[];
 const pos=createPos({statePath:path.join(tmp,'test.sqlite'),catalog:async()=>({}),store:async d=>{calls.push(d);return d.action==='pricing'?{plans:[{key:'plan6',total:12500}]}:{payment_url:'https://fusionbikes.com.ar/?fbpos_vps_open='+'a'.repeat(48)};}});
 const items=[{id:21,qty:2}];await pos('pricing',{items},'one');await pos('pricing',{items},'one');assert.equal(calls.length,1);
 await pos('draft-write',{version:0,sale:{items,plan:'plan6'}},'one');assert.equal((await pos('draft-read',{},'one')).sale.plan,'plan6');
 await pos('prepare',{operation:op,items,price_key:'plan6',expected_total:12500},'one');assert.equal(calls[1].price_key,'plan6');assert.equal(calls[1].expected_total,12500);
 await assert.rejects(pos('prepare',{operation:op,items,price_key:'plan24',expected_total:12500},'one'),e=>e.code==='operation_conflict');
 await assert.rejects(pos('manual-receipt',{operation:op,confirmed:false},'one'));await assert.rejects(pos('fulfillment',{operation:op,mode:'delivered'},'one'));
 await pos('manual-receipt',{operation:op,confirmed:true},'one');assert.equal(calls.at(-1).action,'manual-receipt');
});
test('Session renewal authenticates admin and does not mutate POS',async t=>{
 let admin=true,calls=0;const secret='x'.repeat(64),cookie='connect.sid=qa';const auth=http.createServer((q,r)=>r.end(JSON.stringify({ok:true,user:'qa',is_admin:admin})));await new Promise(r=>auth.listen(0,'127.0.0.1',r));
 const gw=createGateway({secret,upstreamHost:'127.0.0.1',authPort:auth.address().port,posEnabled:true,posHandle:async()=>{calls++;return {};}});await new Promise(r=>gw.listen(0,'127.0.0.1',r));t.after(()=>{gw.close();auth.close();});
 const base='http://127.0.0.1:'+gw.address().port+prefix+'/wp-json/fbpos/v2/';const r=await fetch(base+'session',{headers:{cookie}});assert.equal((await r.json()).csrf,csrfToken(secret,'qa',cookie));assert.equal(calls,0);
 const denied=await fetch(base+'manual-receipt',{method:'POST',headers:{cookie,origin:'https://herramientas.fusionbikes.com.ar','content-type':'application/json','x-fusion-csrf':'expired'},body:'{}'});assert.equal((await denied.json()).code,'pos_csrf');assert.equal(calls,0);
 admin=false;assert.equal((await fetch(base+'session',{headers:{cookie}})).status,403);
});
