CREATE ROLE plataforma_migrador LOGIN PASSWORD 'migrador' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE plataforma_app LOGIN PASSWORD 'app' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE DATABASE plataforma OWNER plataforma_migrador;
REVOKE ALL ON DATABASE plataforma FROM PUBLIC;
GRANT CONNECT ON DATABASE plataforma TO plataforma_app;
